# SPDX-FileCopyrightText: 2023 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0

- id: lint
  name: gettext-go-lint
  description: Gettext Linter for go
  entry: gettext-go-lint
  types: [go]
  language: golang
